"""fix_ticket_status_type

Revision ID: 0ab86c3e2aeb
Revises: 9385ab91c52f
Create Date: 2025-12-06 14:43:35.915472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ab86c3e2aeb'
down_revision: Union[str, Sequence[str], None] = '9385ab91c52f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'),
               type_=sa.String(),
               existing_nullable=True,
               postgresql_using='priority::text')
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('BACKLOG', 'TODO', 'IN_PROGRESS', 'CODE_REVIEW', 'DONE', name='ticketstatus'),
               type_=sa.String(),
               existing_nullable=True,
               postgresql_using='status::text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('BACKLOG', 'TODO', 'IN_PROGRESS', 'CODE_REVIEW', 'DONE', name='ticketstatus'),
               existing_nullable=True)
    op.alter_column('tickets', 'priority',
               existing_type=sa.String(),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'),
               existing_nullable=True)
    # ### end Alembic commands ###
