"""Add onboarding_completed_tasks to User

Revision ID: 377100619abe
Revises: 0ab86c3e2aeb
Create Date: 2026-01-17 08:29:53.407860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377100619abe'
down_revision: Union[str, Sequence[str], None] = '0ab86c3e2aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE tickets ALTER COLUMN priority TYPE ticketpriority USING priority::ticketpriority")
    op.execute("ALTER TABLE tickets ALTER COLUMN status TYPE ticketstatus USING status::ticketstatus")
    op.add_column('users', sa.Column('onboarding_completed_tasks', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed_tasks')
    op.alter_column('tickets', 'status',
               existing_type=sa.Enum('BACKLOG', 'TODO', 'IN_PROGRESS', 'IN_TEST', 'PO_REVIEW', 'DONE', name='ticketstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('tickets', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticketpriority'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
