"""add_rag_metadata_to_user

Revision ID: 51e87b900a9b
Revises: 4a1b2c3d4e5f
Create Date: 2026-01-18 09:41:52.618165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e87b900a9b'
down_revision: Union[str, Sequence[str], None] = '4a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('repo_full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_indexed_commit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_indexed_commit')
    op.drop_column('users', 'repo_full_name')
    # ### end Alembic commands ###
