"""replace_github_auth_with_standard_auth

Revision ID: 95bd48e8edb1
Revises: 51e87b900a9b
Create Date: 2026-01-31 12:45:54.264594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95bd48e8edb1'
down_revision: Union[str, Sequence[str], None] = '51e87b900a9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_column('users', 'access_token')
    op.drop_column('users', 'github_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
